# Default values for logic-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

commitSha: ""
replicaCount: 1

teamId: 11

image:
  repository: gitlab.stud.atlantis.ugent.be:5050/devops-2021/devops-team11/logic-service
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: 
  - name: gitlab-credentials
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 80

resources:
  {}

logicService:
  secureEndpoints: "false"
  secureKey: ""

metrics:
  enabled: true
  port: 1234

